[colors.primary]
foreground = "#ebdbb2"
background = "#1d2021"
[colors.normal]
black      = "#191b1c"
red        = "#ea6962"
green      = "#a9b665"
yellow     = "#d8a657"
blue       = "#7daea3"
magenta    = "#d3869b"
cyan       = "#89b482"
white      = "#a89984"
[colors.bright]
black      = "#928374"
red        = "#ea6962"
green      = "#a9b665"
yellow     = "#d8a657"
blue       = "#7daea3"
magenta    = "#d3869b"
cyan       = "#89b482"
white      = "#ebdbb2"
